package com.tamtam.android.tamtam.services.json;

import com.tamtam.android.tamtam.model.ThingObject;
import com.tamtam.android.tamtam.model.ThingObject.PositionObject;
import com.tamtam.android.tamtam.model.ThingObject.PriceObject;
import com.tamtam.android.tamtam.model.UserObject;
import com.tamtam.android.tamtam.services.json.JsonThingConverter;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;


/**
 * Created by fcng1847 on 11/01/17.
 */
public class JsonThingConverterTest {


    //// TODO: 14/01/17 replace by values generated by a mock Repository
    private static final String jsonThingString1 = "{\"thingId\":\"thing1\"," +
            "\"pict\":\"AAaaaIaAMaBASEa64aENCODEDaaaag==\"," +
            "\"description\":\"cest un premier truc\"," +
            "\"price\":{\"currency\":489,\"price\":10.10}," +
            "\"position\":{\"lon\":7.05289,\"lat\":43.6166}," +
            "\"stuck\":false}";
    private static final String jsonThingString2 = "{\"thingId\":\"thing2\"," +
            "\"pict\":\"AAaaaIaAMaBASEa64aENCODEDaaaag==\"," +
            "\"description\":\"cest un deuxieme truc\"," +
            "\"price\":{\"currency\":489,\"price\":20.20}," +
            "\"position\":{\"lon\":7.05334,\"lat\":43.61664}," +
            "\"stuck\":false}";
    private static final String jsonThingString3 = "{\"thingId\":\"thing3\"," +
            "\"pict\":\"AAaaaIaAMaBASEa64aENCODEDaaaag==\"," +
            "\"description\":\"cest un troisieme truc\"," +
            "\"price\":{\"currency\":489,\"price\":30.30}," +
            "\"position\":{\"lon\":7.12153,\"lat\":43.65839}," +
            "\"stuck\":false}";

    private static final String jsonThingsArray = "[" + jsonThingString1 + "," +
                                                       jsonThingString2 + "," +
                                                       jsonThingString3 + "]";

    private static PositionObject positionObject1 =
            new PositionObject(7.05289, 43.6166);
    private static PriceObject priceObject1 =
            new PriceObject(489, 10.10);
    private static ThingObject thingObject1 = new ThingObject.ThingBuilder()
            .thingId("thing1")
            .pict("AAaaaIaAMaBASEa64aENCODEDaaaag==")
            .description("cest un premier truc")
            .position(positionObject1)
            .price(priceObject1)
            .stuck(false)
            .build();

    private static ThingObject thingObject2 = new ThingObject.ThingBuilder()
            .thingId("thing2")
            .pict("AAaaaIaAMaBASEa64aENCODEDaaaag==")
            .description("cest un deuxieme truc")
            .position(new PositionObject(7.05334, 43.61664))
            .price(new PriceObject(489, 20.20))
            .stuck(false)
            .build();

    private static ThingObject thingObject3 = new ThingObject.ThingBuilder()
            .thingId("thing3")
            .pict("AAaaaIaAMaBASEa64aENCODEDaaaag==")
            .description("cest un troisieme truc")
            .position(new PositionObject(7.12153, 43.65839))
            .price(new PriceObject(489, 30.30))
            .stuck(false)
            .build();

    private static List<ThingObject> thingObjects =
            Arrays.asList(thingObject1, thingObject2, thingObject3);



    private JsonThingConverter jsonThingConverter;

    @Before
    public void constructor() throws Exception {
        jsonThingConverter = new JsonThingConverter();
    }

    @Test
    public void fromJson() throws Exception {
        ThingObject thing1 = jsonThingConverter.fromJson(jsonThingString1);

        assertEquals("thing1", thing1.getThingId());
        assertEquals(thingObject1, thing1);
    }

    @Test
    public void toJson() throws Exception {
        String resultJson = jsonThingConverter.toJson(thingObject1);
        assertTrue(ParsableJson(resultJson));
        assertTrue(resultJson.contains(JsonThingConverter.ID_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.CURRENCY_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.DESCRIPTION_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.LATITUDE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.LONGITUDE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.PICTURE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.PRICE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.POSITION_OBJ_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.PRICE_OBJ_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.STUCK_KEYNAME));

    }

    @Test
    public void fomJsonToJson() throws Exception {
        String resultJson = jsonThingConverter.toJson(
                jsonThingConverter.fromJson(jsonThingString1));
        assertTrue(ParsableJson(resultJson));
        assertTrue(resultJson.contains(JsonThingConverter.ID_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.CURRENCY_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.DESCRIPTION_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.LATITUDE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.LONGITUDE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.PICTURE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.PRICE_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.POSITION_OBJ_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.PRICE_OBJ_KEYNAME));
        assertTrue(resultJson.contains(JsonThingConverter.STUCK_KEYNAME));

    }

    @Test
    public void toJsonFromJson() throws Exception {
        ThingObject generatedThing = jsonThingConverter.fromJson(
                jsonThingConverter.toJson(thingObject1));

        assertEquals(thingObject1, generatedThing);
    }

    @Test
    public void fromJsonArray() throws Exception{
        List<ThingObject> generatedThingsList = jsonThingConverter.fromJsonArray(jsonThingsArray);
        assertEquals(thingObjects, generatedThingsList);
    }

    @Test
    public void fromEmptyJsonArray() throws Exception{
        List<ThingObject> emptyList = new ArrayList<ThingObject>();
        List<ThingObject> generatedThingsList = jsonThingConverter.fromJsonArray("[]");
        assertEquals(emptyList, generatedThingsList);
    }

    @Test
    public void fromEmptyJson() throws Exception{
        assertNull(jsonThingConverter.fromJson("{}"));
    }

    @Test
    public void fromMalformedJsonArray() throws Exception{
        assertNull(jsonThingConverter.fromJsonArray("[%*sdcccq]"));
    }


    @Test
    public void fromMalformedJson() throws Exception{
        assertNull(jsonThingConverter.fromJson("{toto%*sd:cccq}"));
    }

    /***
     * ugly utility function to verify that a Json String is parsable
     * @param test
     * @return true if parsable by {@link JSONObject} or {@link JSONArray}, false otherwise
     */
    boolean ParsableJson(String test) {
        try {
            new JSONObject(test);
        } catch (JSONException ex) {
            try {
                new JSONArray(test);
            } catch (JSONException ex1) {
                return false;
            }
        }
        return true;
    }
}